/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Accountant;
import Model.PayrollBreakdown;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Robert
 */
public class GenerateKardexUI extends javax.swing.JFrame {

    /**
     * Creates new form GenerateKardexUI
     */
    public GenerateKardexUI() {
        initComponents();
        setVisible(true);
        
        accountant = new Accountant(this);
    }
    
    public void fillPayrollBreakdownTable(ArrayList<PayrollBreakdown> kardex){
        
        Vector <String> title = new Vector<String>();
        Vector<Vector<Object>> data= new Vector<Vector<Object>>();
        
        title.add("Id Desglose");
        title.add("Clave Empleado");
        title.add("ISR");
        title.add("Seguro");
        title.add("Aguinaldo");
        title.add("Vacaciones");
        title.add("Prima dominical");
        title.add("Dias trabajados");
        title.add("Total");
        title.add("Salario");
        title.add("Fecha");
        
        SimpleDateFormat dateFormat = new SimpleDateFormat();
        for(int i=0; i<kardex.size(); i++){
            Vector<Object> row= new Vector<Object>();
            
            row.add((String.valueOf(kardex.get(i).getDesgloseId() ) ) );
            row.add((String.valueOf(kardex.get(i).getEmployeeId() ) ) );
            row.add((String.valueOf(kardex.get(i).getRetention().getISR() ) ) );
            row.add((String.valueOf(kardex.get(i).getRetention().getTaxPerIMSS() ) ) );
            row.add((String.valueOf(kardex.get(i).getBonus().getChristmasBox() ) ) );
            row.add((String.valueOf(kardex.get(i).getBonus().getHolidayBonus() ) ) );
            row.add((String.valueOf(kardex.get(i).getBonus().getDominical() ) ) );
            row.add((String.valueOf(kardex.get(i).getWorkedDays() ) ) );
            row.add((String.valueOf(kardex.get(i).getTotalPayment() ) ) );
            row.add((String.valueOf(kardex.get(i).getIntegratedWage() ) ) );
            row.add((dateFormat.format(kardex.get(i).getBreakdownDate() ) ) );
            
            data.add(row);
        }
        
        DefaultTableModel modelo= new javax.swing.table.DefaultTableModel(data, title);
        payrollBreakdownTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        employeeIdField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        payrollBreakdownTable = new javax.swing.JTable();
        generateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kardex de empleado");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Clave de empleado:");

        payrollBreakdownTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Clave Empleado", "ISR", "Seguro", "Aguinaldo", "Vacaciones", "Prima dominical", "Dias trabajados", "Total", "Salario", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(payrollBreakdownTable);

        generateBtn.setText("Generar Kardex");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(173, 173, 173))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(employeeIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generateBtn)))
                .addGap(298, 298, 298))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateBtn))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        // TODO add your handling code here:
        String employeeIdInput = employeeIdField.getText();
        try {
            String operationStatus = accountant.generateKardex(employeeIdInput);
            JOptionPane.showMessageDialog(null, operationStatus);
        } catch (ParseException ex) {
            Logger.getLogger(GenerateKardexUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error al convertir la fecha");
        }
    }//GEN-LAST:event_generateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    private Accountant accountant;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField employeeIdField;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable payrollBreakdownTable;
    // End of variables declaration//GEN-END:variables
}
