/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.ValidateMainMenuInterface;
import javax.swing.JOptionPane;

/**
 *
 * @author che_i
 */
public class MainMenuUI extends javax.swing.JFrame {

    /** Creates new form MainMenuIU */
    public MainMenuUI(ValidateMainMenuInterface validateMainMenu) {
        initComponents();
        this.setVisible(true);
        this.validateMainMenu = validateMainMenu;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        RentButton = new javax.swing.JButton();
        RestorationButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        ClientButton = new javax.swing.JMenu();
        clientButton = new javax.swing.JMenuItem();
        filmsButton = new javax.swing.JMenuItem();
        employeeButton = new javax.swing.JMenuItem();
        usersButton = new javax.swing.JMenuItem();
        ReportsMenu = new javax.swing.JMenu();
        payrollMenu = new javax.swing.JMenu();
        SessionMenu = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hollywood World - Main Menu");

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 3, 48)); // NOI18N
        jLabel3.setText("Hollywood World!");

        RentButton.setFont(new java.awt.Font("Berlin Sans FB", 3, 18)); // NOI18N
        RentButton.setText("Rent");
        RentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentButtonActionPerformed(evt);
            }
        });

        RestorationButton.setFont(new java.awt.Font("Berlin Sans FB", 3, 24)); // NOI18N
        RestorationButton.setText("Restoration");
        RestorationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestorationButtonActionPerformed(evt);
            }
        });

        ClientButton.setText("Manage");

        clientButton.setText("Clients");
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });
        ClientButton.add(clientButton);

        filmsButton.setText("Films");
        filmsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmsButtonActionPerformed(evt);
            }
        });
        ClientButton.add(filmsButton);

        employeeButton.setText("Employees");
        employeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeButtonActionPerformed(evt);
            }
        });
        ClientButton.add(employeeButton);

        usersButton.setText("Users");
        usersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersButtonActionPerformed(evt);
            }
        });
        ClientButton.add(usersButton);

        jMenuBar1.add(ClientButton);

        ReportsMenu.setText("Reports");
        jMenuBar1.add(ReportsMenu);

        payrollMenu.setText("Payroll");
        jMenuBar1.add(payrollMenu);

        SessionMenu.setText("Session");
        jMenuBar1.add(SessionMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(RestorationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel3)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RestorationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGap(0, 55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButtonActionPerformed
        // TODO add your handling code here:
        if(validateMainMenu.userHasHumanResourcesPermissions()){
            JOptionPane.showMessageDialog(null, "Welcome, human resources!!");
        }else{
            JOptionPane.showMessageDialog(null, "You cannot access this function");
        }
    }//GEN-LAST:event_usersButtonActionPerformed

    private void RentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentButtonActionPerformed
        // TODO add your handling code here:
        if(validateMainMenu.userHasRenterPermissions() ||
                validateMainMenu.userHasManagerPermissions()){
            JOptionPane.showMessageDialog(null, "Welcome, renter/manager!");
        }else{
            JOptionPane.showMessageDialog(null, "You cannot access this function");
        }
    }//GEN-LAST:event_RentButtonActionPerformed

    private void RestorationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestorationButtonActionPerformed
        // TODO add your handling code here:
        if(validateMainMenu.userHasRenterPermissions() ||
                validateMainMenu.userHasManagerPermissions()){
            JOptionPane.showMessageDialog(null, "Welcome, renter/manager!");
        }else{
            JOptionPane.showMessageDialog(null, "You cannot access this function");
        }
    }//GEN-LAST:event_RestorationButtonActionPerformed

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        // TODO add your handling code here:
        if(validateMainMenu.userHasRenterPermissions() ||
                validateMainMenu.userHasManagerPermissions()){
            JOptionPane.showMessageDialog(null, "Welcome, renter/manager!");
        }else{
            JOptionPane.showMessageDialog(null, "You cannot access this function");
        }
    }//GEN-LAST:event_clientButtonActionPerformed

    private void filmsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmsButtonActionPerformed
        // TODO add your handling code here:
        if(validateMainMenu.userHasManagerPermissions()){
            JOptionPane.showMessageDialog(null, "Welcome, manager!");
        }else{
            JOptionPane.showMessageDialog(null, "You cannot access this function");
        }
    }//GEN-LAST:event_filmsButtonActionPerformed

    private void employeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeButtonActionPerformed
        // TODO add your handling code here:
        if(validateMainMenu.userHasHumanResourcesPermissions()){
            JOptionPane.showMessageDialog(null, "Human Resources!");
        }else{
            JOptionPane.showMessageDialog(null, "You cannot access this function");
        }
    }//GEN-LAST:event_employeeButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ClientButton;
    private javax.swing.JButton RentButton;
    private javax.swing.JMenu ReportsMenu;
    private javax.swing.JButton RestorationButton;
    private javax.swing.JMenu SessionMenu;
    private javax.swing.JMenuItem clientButton;
    private javax.swing.JMenuItem employeeButton;
    private javax.swing.JMenuItem filmsButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu payrollMenu;
    private javax.swing.JMenuItem usersButton;
    // End of variables declaration//GEN-END:variables
    private ValidateMainMenuInterface validateMainMenu;
}
