/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UserServiceAgent;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class ModifyUserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserUI
     */
    public ModifyUserForm() {
        
        initComponents();
        this.setVisible(true);
        existingUserInfoPanel.setVisible(false);
        
        this.userServiceAgent = new UserServiceAgent(this);
    }
    
    public void fillExistingUserForm(User user){
        this.existingUserInfoPanel.setVisible(true);
        editNameTxt.setText(user.getName());
        editLastNameTxt.setText(user.getLastName());
        editUserNameTxt.setText(user.getUserName());
        editPermissions.setSelectedIndex(
            getPermissionIndex(user.getPermissions() )
            );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        editUserPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchUserNameTxt = new javax.swing.JTextField();
        searchUserBtn = new javax.swing.JToggleButton();
        existingUserInfoPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        editNameTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        editLastNameTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editUserNameTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        editPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        editPermissions = new javax.swing.JComboBox<>();
        saveChangesBtn = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hollywood World - Manage Users");
        setResizable(false);

        jLabel18.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel18.setText("Edit user");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("User name:");

        searchUserBtn.setText("Search");
        searchUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Name:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Last name:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("User name:");

        editUserNameTxt.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Password:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Permissions:");

        editPermissions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Human Resources", "Manager", "Renter" }));

        saveChangesBtn.setText("Save changes");
        saveChangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout existingUserInfoPanelLayout = new javax.swing.GroupLayout(existingUserInfoPanel);
        existingUserInfoPanel.setLayout(existingUserInfoPanelLayout);
        existingUserInfoPanelLayout.setHorizontalGroup(
            existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, existingUserInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveChangesBtn)
                .addGap(48, 48, 48))
            .addGroup(existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(existingUserInfoPanelLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addGroup(existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editPermissions, 0, 137, Short.MAX_VALUE)
                        .addComponent(editPassword)
                        .addComponent(editUserNameTxt)
                        .addComponent(editLastNameTxt)
                        .addComponent(editNameTxt))
                    .addContainerGap(111, Short.MAX_VALUE)))
        );
        existingUserInfoPanelLayout.setVerticalGroup(
            existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, existingUserInfoPanelLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(saveChangesBtn)
                .addContainerGap())
            .addGroup(existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(existingUserInfoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(editNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(editLastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(editUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(editPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(existingUserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(editPermissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout editUserPanelLayout = new javax.swing.GroupLayout(editUserPanel);
        editUserPanel.setLayout(editUserPanelLayout);
        editUserPanelLayout.setHorizontalGroup(
            editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUserPanelLayout.createSequentialGroup()
                .addGroup(editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editUserPanelLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel18))
                    .addGroup(editUserPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(existingUserInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editUserPanelLayout.setVerticalGroup(
            editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUserPanelLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(searchUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(existingUserInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(editUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Guarda los cambios hechos a un usuario existente
    private void saveChangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesBtnActionPerformed
        
        String[] userInput = gatherAllUserInput();
        
        String operationStatus = 
                userServiceAgent.Modification(userInput);
        JOptionPane.showMessageDialog(null, operationStatus);
    }//GEN-LAST:event_saveChangesBtnActionPerformed

    //Busca los datos de usuario existentes y llena el formulario con los datos
    private void searchUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserBtnActionPerformed
        
        //Antes de obtener la información, validar
        String userName = searchUserNameTxt.getText();
        String operationStatus = 
                userServiceAgent.Retrieval(userName);
        JOptionPane.showMessageDialog(null, operationStatus);
        
    }//GEN-LAST:event_searchUserBtnActionPerformed

    private String[] gatherAllUserInput(){
        
        String[] userInputs = new String[5];
        
        userInputs[0] = editNameTxt.getText();
        userInputs[1] = editLastNameTxt.getText();
        userInputs[2] = editUserNameTxt.getText();
        userInputs[3] = String.valueOf(this.editPassword.getPassword() );
        userInputs[4] = this.editPermissions.getSelectedItem().toString();
        
        return userInputs;
        
    }
    
    //Obtiene el índice correspondiente del comboBox de permisos de usuario
    private int getPermissionIndex(String permissions){
        
        int permissionIndex;
        switch(permissions){
            case "Administrator" : permissionIndex = 0;
                break;
            case "Human Resources" : permissionIndex = 1;
                break;
            case "Manager" : permissionIndex = 2;
                break;
            case "Renter" : permissionIndex = 3;
                break;
            default : permissionIndex = ERROR;
        }
        return permissionIndex;
    }
    
    
    
    


    private UserServiceAgent userServiceAgent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editLastNameTxt;
    private javax.swing.JTextField editNameTxt;
    private javax.swing.JPasswordField editPassword;
    private javax.swing.JComboBox<String> editPermissions;
    private javax.swing.JTextField editUserNameTxt;
    private javax.swing.JPanel editUserPanel;
    private javax.swing.JPanel existingUserInfoPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton saveChangesBtn;
    private javax.swing.JToggleButton searchUserBtn;
    private javax.swing.JTextField searchUserNameTxt;
    // End of variables declaration//GEN-END:variables
    
}
