package View;

import Controller.InventoryControl;
import Model.MovieProfile;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 * 
 * Interfaz gráfica del manejador de películas. Permite agregar
 * películas al inventario, crear nuevos perfiles de películas y editarlos
 */
public class ModifyMovieProfileForm extends javax.swing.JFrame {

    public ModifyMovieProfileForm() {
        initComponents(); //Componentes visuales de swing
        this.setVisible(true);
        this.existingProfilePanel.setVisible(false);
        
        this.inventoryControl = new InventoryControl(this );
    }
    
    public void fillExistingProfileForm( MovieProfile movieProfile ){
        
        existingProfilePanel.setVisible(true);
        editProfileTitleTxt.setText(movieProfile.getTitle() );
        editReleaseDate.setDate(movieProfile.getReleaseDate() );
        editRatingTxt.setText(movieProfile.getRating() );
        editDescriptionTxt.setText(movieProfile.getDescription() );
        editRuntimeTxt.setText(movieProfile.getRunTime() );
        editSerialCodeTxt.setText(movieProfile.getSerialCode() );        
    }
    
    public void clearFields() {
        
        searchSerialTxt.setText("");
        editProfileTitleTxt.setText("");
        editReleaseDate.setDate(null);
        editRatingTxt.setText("");
        editDescriptionTxt.setText("");
        editRuntimeTxt.setText("");
        editSerialCodeTxt.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        searchSerialTxt = new javax.swing.JTextField();
        searchSerialBtn = new javax.swing.JButton();
        existingProfilePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        editProfileTitleTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        editReleaseDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        editRatingTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        editDescriptionTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        editRuntimeTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        editSerialCodeTxt = new javax.swing.JTextField();
        saveProfileChangeBtn = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hollywood World - Manage Movies");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Código de serie de perfil existente");

        searchSerialBtn.setText("Buscar");
        searchSerialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSerialBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Titulo de película:");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Fecha de lanzamiento:");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Clasificación:");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Descripción:");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Duración:");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Código de serie:");

        editSerialCodeTxt.setEditable(false);

        saveProfileChangeBtn.setText("Guardar cambios");
        saveProfileChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProfileChangeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout existingProfilePanelLayout = new javax.swing.GroupLayout(existingProfilePanel);
        existingProfilePanel.setLayout(existingProfilePanelLayout);
        existingProfilePanelLayout.setHorizontalGroup(
            existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingProfilePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveProfileChangeBtn)
                    .addGroup(existingProfilePanelLayout.createSequentialGroup()
                        .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editProfileTitleTxt)
                            .addComponent(editReleaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editRatingTxt)
                            .addComponent(editDescriptionTxt)
                            .addComponent(editRuntimeTxt)
                            .addComponent(editSerialCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        existingProfilePanelLayout.setVerticalGroup(
            existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(editProfileTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(editReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(editRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(editDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(editRuntimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(editSerialCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveProfileChangeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel19.setText("Modificar informacion de película");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(existingProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchSerialBtn)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(searchSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchSerialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existingProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveProfileChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProfileChangeBtnActionPerformed
        
        String[] userInputs = gatherAllUserInput();

        String operationStatus;
        try {
            operationStatus = inventoryControl.modifyProfile(userInputs);
            JOptionPane.showMessageDialog(null, operationStatus);
        } catch (ParseException ex) {
            Logger.getLogger(ModifyMovieProfileForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveProfileChangeBtnActionPerformed

    private void searchSerialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSerialBtnActionPerformed
        
        String selectedSerial = searchSerialTxt.getText();
        
        String operationStatus = inventoryControl.retrieveInformation(selectedSerial);
        JOptionPane.showMessageDialog(null, operationStatus);
    }//GEN-LAST:event_searchSerialBtnActionPerformed
    
    private String[] gatherAllUserInput(){
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String[] userInput = new String[6];
        userInput[0] = editProfileTitleTxt.getText();
        userInput[1] = dateFormat.
                format(editReleaseDate.getDate() );
        userInput[2] = editRatingTxt.getText();
        userInput[3] = editDescriptionTxt.getText();
        userInput[4] = editRuntimeTxt.getText();
        userInput[5] = editSerialCodeTxt.getText();
        
        return userInput;
    }
   
    private InventoryControl inventoryControl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editDescriptionTxt;
    private javax.swing.JTextField editProfileTitleTxt;
    private javax.swing.JTextField editRatingTxt;
    private org.jdesktop.swingx.JXDatePicker editReleaseDate;
    private javax.swing.JTextField editRuntimeTxt;
    private javax.swing.JTextField editSerialCodeTxt;
    private javax.swing.JPanel existingProfilePanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JToggleButton saveProfileChangeBtn;
    private javax.swing.JButton searchSerialBtn;
    private javax.swing.JTextField searchSerialTxt;
    // End of variables declaration//GEN-END:variables
}
