package View;

import Controller.MovieAdministrator;
import Model.Movie;
import Model.MovieProfile;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 * 
 * Interfaz gráfica del manejador de películas. Permite agregar
 * películas al inventario, crear nuevos perfiles de películas y editarlos
 */
public class MovieUI extends javax.swing.JFrame {

    public MovieUI() {
        initComponents(); //Componentes visuales de swing
        this.setVisible(true);
        this.existingProfilePanel.setVisible(false);
        
        this.newMovie = new Movie(MovieAdministrator.generateNextMovieId() );
        fillMovieIdField();
        this.newProfile = new MovieProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        inventoryPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addSerialCodeTxt = new javax.swing.JTextField();
        amountToAddTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        movieId = new javax.swing.JTextField();
        addMoviesBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        newProfilePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newProfileTitleTxt = new javax.swing.JTextField();
        newRatingTxt = new javax.swing.JTextField();
        newDescriptionTxt = new javax.swing.JTextField();
        newRuntimeTxt = new javax.swing.JTextField();
        newSerialcodeTxt = new javax.swing.JTextField();
        addNewProfileBtn = new javax.swing.JButton();
        newReleaseDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel18 = new javax.swing.JLabel();
        editProfilePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        searchSerialTxt = new javax.swing.JTextField();
        searchSerialBtn = new javax.swing.JButton();
        existingProfilePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        editProfileTitleTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        editReleaseDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        editRatingTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        editDescriptionTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        editRuntimeTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        editSerialCodeTxt = new javax.swing.JTextField();
        saveProfileChangeBtn = new javax.swing.JToggleButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hollywood World - Manage Movies");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Movie serial code:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Amount to add:");

        addSerialCodeTxt.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Movie(s) code(s):");

        movieId.setEditable(false);

        addMoviesBtn.setText("Add movies");
        addMoviesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoviesBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel17.setText("Add movies");

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addMoviesBtn)
                            .addGroup(inventoryPanelLayout.createSequentialGroup()
                                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(44, 44, 44)
                                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addSerialCodeTxt)
                                    .addComponent(amountToAddTxt)
                                    .addComponent(movieId, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))))
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel17)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addSerialCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(amountToAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(movieId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(addMoviesBtn)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Add movies to Inventory", inventoryPanel);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Movie title:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Release Date:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Rating:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Description:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Runtime:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Serial code:");

        addNewProfileBtn.setText("Add new profile");
        addNewProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewProfileBtnActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel18.setText("Add movie profile");

        javax.swing.GroupLayout newProfilePanelLayout = new javax.swing.GroupLayout(newProfilePanel);
        newProfilePanel.setLayout(newProfilePanelLayout);
        newProfilePanelLayout.setHorizontalGroup(
            newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProfilePanelLayout.createSequentialGroup()
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newProfilePanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addNewProfileBtn)
                            .addGroup(newProfilePanelLayout.createSequentialGroup()
                                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newProfileTitleTxt)
                                    .addComponent(newRatingTxt)
                                    .addComponent(newDescriptionTxt)
                                    .addComponent(newRuntimeTxt)
                                    .addComponent(newSerialcodeTxt)
                                    .addComponent(newReleaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))))
                    .addGroup(newProfilePanelLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel18)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        newProfilePanelLayout.setVerticalGroup(
            newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(9, 9, 9)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newProfileTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(newRuntimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(newSerialcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(addNewProfileBtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create new profile", newProfilePanel);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Existing profile serial code:");

        searchSerialBtn.setText("Search");
        searchSerialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSerialBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Movie title:");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Release date:");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Rating:");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Description:");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Runtime:");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Serial code:");

        editSerialCodeTxt.setEditable(false);

        saveProfileChangeBtn.setText("Save changes");
        saveProfileChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProfileChangeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout existingProfilePanelLayout = new javax.swing.GroupLayout(existingProfilePanel);
        existingProfilePanel.setLayout(existingProfilePanelLayout);
        existingProfilePanelLayout.setHorizontalGroup(
            existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingProfilePanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveProfileChangeBtn)
                    .addGroup(existingProfilePanelLayout.createSequentialGroup()
                        .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editProfileTitleTxt)
                            .addComponent(editReleaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(editRatingTxt)
                            .addComponent(editDescriptionTxt)
                            .addComponent(editRuntimeTxt)
                            .addComponent(editSerialCodeTxt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        existingProfilePanelLayout.setVerticalGroup(
            existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(editProfileTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(editReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(editRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(editDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(editRuntimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(existingProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(editSerialCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveProfileChangeBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editProfilePanelLayout = new javax.swing.GroupLayout(editProfilePanel);
        editProfilePanel.setLayout(editProfilePanelLayout);
        editProfilePanelLayout.setHorizontalGroup(
            editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfilePanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchSerialBtn)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(editProfilePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(existingProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        editProfilePanelLayout.setVerticalGroup(
            editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(searchSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchSerialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(existingProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit profile", editProfilePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMoviesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoviesBtnActionPerformed
        
        //Antes de obtener la información, validar
        String newMovieSerial = addSerialCodeTxt.getText();
        newMovie.setProfile(
                    MovieAdministrator.getMovieProfileInfo(newMovieSerial)
                    );
        int addAmount = Integer.valueOf(amountToAddTxt.getText() );
        String operationStatus;
        operationStatus = MovieAdministrator.addMoviesToInventory(newMovie, addAmount);
            
        JOptionPane.showMessageDialog(null, operationStatus);
        
    }//GEN-LAST:event_addMoviesBtnActionPerformed

    private void addNewProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewProfileBtnActionPerformed
        
        gatherNewProfileInformation();
        
        if(isEveryInputValid(newProfile) ){
            
            String operationStatus;
            operationStatus = MovieAdministrator.registerMovieProfile(newProfile);

            JOptionPane.showMessageDialog(null, operationStatus);
        }else{
            JOptionPane.showMessageDialog(null, "Invalid profile parameters");
        }    
    }//GEN-LAST:event_addNewProfileBtnActionPerformed

    private void saveProfileChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProfileChangeBtnActionPerformed
        
        gatherExistingProfileInformation();
        
        if(isEveryInputValid(existingProfile) ){
            String operationStatus;
            operationStatus = MovieAdministrator.modifyMovieProfile(existingProfile);
        
            JOptionPane.showMessageDialog(null, operationStatus);
        }else{
            JOptionPane.showMessageDialog(null, "Invalid profile parameters");
        }
        
        
    }//GEN-LAST:event_saveProfileChangeBtnActionPerformed

    private void searchSerialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSerialBtnActionPerformed
        
        String selectedSerial = searchSerialTxt.getText();
        
        existingProfile = MovieAdministrator.getMovieProfileInfo(selectedSerial);
            existingProfilePanel.setVisible(true);
            fillExistingProfileInformation();
    }//GEN-LAST:event_searchSerialBtnActionPerformed

    private void gatherNewProfileInformation(){
        
        String newTitle = newProfileTitleTxt.getText();
        Date newDate = newReleaseDate.getDate();
        String newRating = newRatingTxt.getText();
        String newDescription = newDescriptionTxt.getText();
        String newRuntime = newRuntimeTxt.getText();
        String newSerialcode = newSerialcodeTxt.getText();
        
        newProfile = new MovieProfile(
            newTitle,
            newDate,
            newRating,
            newDescription,
            newRuntime,
            newSerialcode
            );
    }
    
    private void gatherExistingProfileInformation(){
        
        String editTitle = editProfileTitleTxt.getText();
        Date editDate = editReleaseDate.getDate();
        String editRating = editRatingTxt.getText();
        String editDescription = editDescriptionTxt.getText();
        String editRuntime = editRuntimeTxt.getText();
        String editSerialCode = editSerialCodeTxt.getText();
        
        existingProfile = new MovieProfile(
            editTitle,
            editDate,
            editRating,
            editDescription,
            editRuntime,
            editSerialCode
            );
    }
    
    private void fillExistingProfileInformation(){
        
        editProfileTitleTxt.setText(existingProfile.getTitle() );
        editReleaseDate.setDate(existingProfile.getReleaseDate() );
        editRatingTxt.setText(existingProfile.getRating() );
        editDescriptionTxt.setText(existingProfile.getDescription() );
        editRuntimeTxt.setText(existingProfile.getRunTime() );
        editSerialCodeTxt.setText(existingProfile.getSerialCode() );
    }
    
    private void fillMovieIdField(){
        this.movieId.setText(String.valueOf(newMovie.getId() ) );
    }
    
    private boolean isEveryInputValid(MovieProfile profile){
        
        if(isValidInputText( profile.getTitle() )&& 
            isValidInputDate( profile.getReleaseDate() )&&
            isValidInputRating( profile.getRating())&&
            isValidInputText( profile.getDescription() ) &&
            isValidInputText( profile.getRunTime() )&&
            isValidInputSerialCode( profile.getSerialCode() )
        ){
            return true;
        }
        else{
            return false;
        }
    }
    
    private boolean isValidInputText(String input){
        
        if (input.matches("([A-Za-z]|\\s)*") 
            && input.equals(" ") == false 
            && input.equals("") == false){
            return true;
        }else{
            return false;
        }
    }
    
    private boolean isValidInputSerialCode(String input){
        
        if (input.matches("([A-Za-z]|[0-9]|-)*") 
            && input.equals(" ") == false 
            && input.equals("") == false){
            return true;
        }else{
            return false;
        }
    }
    
    private boolean isValidInputRating(String input){
        
        if (input.matches("([A-Z]|[0-9])*") 
            && input.equals(" ") == false 
            && input.equals("") == false){
            return true;
        }else{
            return false;
        }
    }
    
    private boolean isValidInputDate(Date date){
        
        if (date!=null){
            return true;
        }else{
            return false;
        }
    }
    
    private Movie newMovie;
    private MovieProfile newProfile;
    private MovieProfile existingProfile;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMoviesBtn;
    private javax.swing.JButton addNewProfileBtn;
    private javax.swing.JTextField addSerialCodeTxt;
    private javax.swing.JTextField amountToAddTxt;
    private javax.swing.JTextField editDescriptionTxt;
    private javax.swing.JPanel editProfilePanel;
    private javax.swing.JTextField editProfileTitleTxt;
    private javax.swing.JTextField editRatingTxt;
    private org.jdesktop.swingx.JXDatePicker editReleaseDate;
    private javax.swing.JTextField editRuntimeTxt;
    private javax.swing.JTextField editSerialCodeTxt;
    private javax.swing.JPanel existingProfilePanel;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField movieId;
    private javax.swing.JTextField newDescriptionTxt;
    private javax.swing.JPanel newProfilePanel;
    private javax.swing.JTextField newProfileTitleTxt;
    private javax.swing.JTextField newRatingTxt;
    private org.jdesktop.swingx.JXDatePicker newReleaseDate;
    private javax.swing.JTextField newRuntimeTxt;
    private javax.swing.JTextField newSerialcodeTxt;
    private javax.swing.JToggleButton saveProfileChangeBtn;
    private javax.swing.JButton searchSerialBtn;
    private javax.swing.JTextField searchSerialTxt;
    // End of variables declaration//GEN-END:variables
}
