package View;

import Controller.InventoryControl;
import Model.Movie;
import Model.MovieProfile;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 * 
 * Interfaz gráfica del manejador de películas. Permite agregar
 * películas al inventario, crear nuevos perfiles de películas y editarlos
 */
public class RegisterMovieForm extends javax.swing.JFrame {

    public RegisterMovieForm() {
        
        initComponents(); //Componentes visuales de swing
        this.setVisible(true);        
        this.inventoryControl = new InventoryControl(this );
    }
    
    public void fillMovieUpperIdField( int UpperId ) {
        this.movieUpperIdTxt.setText(String.valueOf(UpperId));
    }
    
    public void fillMovieLowerIdField(int LowerId){
        this.movieLowerIdTxt.setText(String.valueOf(LowerId ) );
    }
    
    public void clearField(int lowerId) {
        
        addSerialCodeTxt.setText("");
        amountToAddTxt.setText("1");
        movieLowerIdTxt.setText(String.valueOf(lowerId));
        movieUpperIdTxt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inventoryPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addSerialCodeTxt = new javax.swing.JTextField();
        amountToAddTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        movieLowerIdTxt = new javax.swing.JTextField();
        addMoviesBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        movieUpperIdTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hollywood World - Manage Movies");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Código de serie:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Monto a agregar:");

        addSerialCodeTxt.setToolTipText("");

        amountToAddTxt.setText("1");
        amountToAddTxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                amountToAddTxtCaretUpdate(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Código(s) de película(s)");

        movieLowerIdTxt.setEditable(false);

        addMoviesBtn.setText("Agregar película(s)");
        addMoviesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoviesBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel17.setText("Agregar películas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("-");

        movieUpperIdTxt.setEditable(false);

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addMoviesBtn)
                        .addGroup(inventoryPanelLayout.createSequentialGroup()
                            .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(44, 44, 44)
                            .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addSerialCodeTxt)
                                .addComponent(amountToAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(inventoryPanelLayout.createSequentialGroup()
                                    .addComponent(movieLowerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(movieUpperIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel17)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addSerialCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(amountToAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(movieLowerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(movieUpperIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(addMoviesBtn)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inventoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMoviesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoviesBtnActionPerformed
        
        String[] userInputs = gatherAllUserInput();
        
        String operationStatus;
        try {
            operationStatus = inventoryControl.addToInventory(userInputs);            
            JOptionPane.showMessageDialog(null, operationStatus);   
        } catch (ParseException ex) {
            Logger.getLogger(RegisterMovieForm.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_addMoviesBtnActionPerformed

    private void amountToAddTxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_amountToAddTxtCaretUpdate
        inventoryControl.modifyMovieAmount(amountToAddTxt.getText());
    }//GEN-LAST:event_amountToAddTxtCaretUpdate
    
    private String[] gatherAllUserInput(){
        
        String[] userInput = new String[3];
        userInput[0] = addSerialCodeTxt.getText();
        userInput[1] = amountToAddTxt.getText();
        userInput[2] = movieLowerIdTxt.getText();
        
        return userInput;
    }
    
    private InventoryControl inventoryControl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMoviesBtn;
    private javax.swing.JTextField addSerialCodeTxt;
    private javax.swing.JTextField amountToAddTxt;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField movieLowerIdTxt;
    private javax.swing.JTextField movieUpperIdTxt;
    // End of variables declaration//GEN-END:variables
}
