package View;

import Controller.ClientAdministrator;
import Model.Client;
import Model.ClientMembership;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class RegisterClientForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientUI
     */
    public RegisterClientForm() {
        
        initComponents(); //Componentes visuales de Swing
        this.setVisible(true);
        this.existingClientInfoPanel.setVisible(false);
        
        this.newClient = new Client(
            new ClientMembership(
                    ClientAdministrator.generateNextMembershipId(),
                    "Active"
                )
            );
        fillMembershipField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newClientPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newNameTxt = new javax.swing.JTextField();
        newLastNameTxt = new javax.swing.JTextField();
        newTelephoneTxt = new javax.swing.JTextField();
        newAddressTxt = new javax.swing.JTextField();
        newMembershipTxt = new javax.swing.JTextField();
        registerNewClientBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hollywood World - Manage Clients");
        setResizable(false);

        jLabel17.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel17.setText("Client Registration");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Last name:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Telephone:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Membership number:");

        newMembershipTxt.setEditable(false);

        registerNewClientBtn.setText("Register new client");
        registerNewClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewClientBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newClientPanelLayout = new javax.swing.GroupLayout(newClientPanel);
        newClientPanel.setLayout(newClientPanelLayout);
        newClientPanelLayout.setHorizontalGroup(
            newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClientPanelLayout.createSequentialGroup()
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newClientPanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel17))
                    .addGroup(newClientPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newNameTxt)
                            .addComponent(newLastNameTxt)
                            .addComponent(newTelephoneTxt)
                            .addComponent(newAddressTxt)
                            .addComponent(newMembershipTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newClientPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registerNewClientBtn)
                .addGap(85, 85, 85))
        );
        newClientPanelLayout.setVerticalGroup(
            newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newLastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newTelephoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newMembershipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(registerNewClientBtn)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(newClientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(newClientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerNewClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewClientBtnActionPerformed
        
        gatherNewClientInformation();
        
        if(isEveryInputValid(newClient) ){
            
            String operationStatus;
            operationStatus= ClientAdministrator.addClient(newClient);
            JOptionPane.showMessageDialog(null, operationStatus);
            
        }else{
            JOptionPane.showMessageDialog(null, "Invalid client parameters");
        }
        
    }//GEN-LAST:event_registerNewClientBtnActionPerformed

    private void gatherNewClientInformation(){
        
        newClient.setName(newNameTxt.getText() );
        newClient.setLastName(newLastNameTxt.getText() ); 
        newClient.setTelephone(newTelephoneTxt.getText() );
        newClient.setAddress(newAddressTxt.getText() );
        
    }
    
    private void gatherExistingClientInformation(){
        
        existingClient.setName(editNameTxt.getText() );
        existingClient.setLastName(editLastNameTxt.getText() );
        existingClient.setTelephone(editTelephoneTxt.getText() );
        existingClient.setAddress(editAddressTxt.getText());
        
        int currentId = existingClient.getMembership().getId();
        String currentStatus = String.valueOf(
                membershipStatus.getSelectedItem() 
                );
        
        existingClient.setMembership(
                new ClientMembership(currentId, currentStatus)
                );
        
    }
    
    private void fillMembershipField(){
        
        newMembershipTxt.setText(
                String.valueOf(newClient.getMembership().getId() ) );
    }
    
    private void fillExistingClientForm(){
        
        editNameTxt.setText(existingClient.getName() );
        editLastNameTxt.setText(existingClient.getLastName() );
        editTelephoneTxt.setText(existingClient.getTelephone() );
        editAddressTxt.setText(existingClient.getAddress() );
        
        String membershipNumber = String.valueOf(
            existingClient.getMembership().getId()
            );
        
        editMembershipTxt.setText(membershipNumber);
        
        membershipStatus.setSelectedIndex(
            getStatusIndex(existingClient.getMembership().getStatus() )
            );
    }
    
    private int getStatusIndex(String membershipStatus){
        
        int statusIndex;
        
        switch(membershipStatus){
            case "Active" : statusIndex = 0;
                break;
            case "Inactive" : statusIndex = 1;
                break;
            default : statusIndex = ERROR;
        }
        return statusIndex;
    }
    
    private boolean isEveryInputValid(Client client){
        if(isValidInputText( client.getName() )
            && isValidInputText( client.getLastName() )
            && isValidInputTelephone( client.getTelephone() )
            && isValidInputAddress( client.getAddress() ) ){
            
            return true;
        }
        else{
            return false;
        }
    }
    
    private boolean isValidInputText(String input){
        if (input.matches("([A-Za-z]|\\s)*") 
            && input.equals(" ") == false 
            && input.equals("") == false){
            return true;
        }else{
            return false;
        }
    }
    
    private boolean isValidInputAddress(String input){
        if (input.matches("([A-Za-z]|\\s|[0-9]|#|-)*") 
            && input.equals(" ") == false 
            && input.equals("") == false){
            return true;
        }else{
            return false;
        }
    }
    
    private boolean isValidInputTelephone(String input){
        if (input.matches("([0-9]|\\s)*") 
            && input.equals(" ") == false 
            && input.equals("") == false){
            return true;
        }else{
            return false;
        }
    }

    private Client newClient;
    private Client existingClient;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField newAddressTxt;
    private javax.swing.JPanel newClientPanel;
    private javax.swing.JTextField newLastNameTxt;
    private javax.swing.JTextField newMembershipTxt;
    private javax.swing.JTextField newNameTxt;
    private javax.swing.JTextField newTelephoneTxt;
    private javax.swing.JButton registerNewClientBtn;
    // End of variables declaration//GEN-END:variables
    
}
