package View;

import Controller.MovieRequestHandler;
import Model.Movie;
import Model.MovieProfile;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 * 
 * Interfaz gráfica del manejador de películas. Permite agregar
 * películas al inventario, crear nuevos perfiles de películas y editarlos
 */
public class RegisterMovieProfileForm extends javax.swing.JFrame {

    public RegisterMovieProfileForm() {
        initComponents(); //Componentes visuales de swing
        this.setVisible(true);
        this.newProfilePanel.setVisible(true);
        
        this.movieRequestHandler = new MovieRequestHandler(this );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        newProfilePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newProfileTitleTxt = new javax.swing.JTextField();
        newRatingTxt = new javax.swing.JTextField();
        newDescriptionTxt = new javax.swing.JTextField();
        newRuntimeTxt = new javax.swing.JTextField();
        newSerialcodeTxt = new javax.swing.JTextField();
        addNewProfileBtn = new javax.swing.JButton();
        newReleaseDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel18 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hollywood World - Registration of movies");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Movie title:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Release Date:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Rating:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Description:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Runtime:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Serial code:");

        addNewProfileBtn.setText("Add new profile");
        addNewProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewProfileBtnActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel18.setText("Add movie profile");

        javax.swing.GroupLayout newProfilePanelLayout = new javax.swing.GroupLayout(newProfilePanel);
        newProfilePanel.setLayout(newProfilePanelLayout);
        newProfilePanelLayout.setHorizontalGroup(
            newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProfilePanelLayout.createSequentialGroup()
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newProfilePanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addNewProfileBtn)
                            .addGroup(newProfilePanelLayout.createSequentialGroup()
                                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newProfileTitleTxt)
                                    .addComponent(newRatingTxt)
                                    .addComponent(newDescriptionTxt)
                                    .addComponent(newRuntimeTxt)
                                    .addComponent(newSerialcodeTxt)
                                    .addComponent(newReleaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))))
                    .addGroup(newProfilePanelLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel18)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        newProfilePanelLayout.setVerticalGroup(
            newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(9, 9, 9)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newProfileTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(newRuntimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(newSerialcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(addNewProfileBtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(newProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(newProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewProfileBtnActionPerformed
        
        String[] userInputs = gatherAllUserInput();
        
        String operationStatus;
        try {
            operationStatus = movieRequestHandler.handleRegistrationProfile(userInputs);
            JOptionPane.showMessageDialog(null, operationStatus);  
        } catch (ParseException ex) {
            Logger.getLogger(RegisterMovieProfileForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addNewProfileBtnActionPerformed

    private String[] gatherAllUserInput(){
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String[] userInput = new String[6];
        userInput[0] = newProfileTitleTxt.getText();
        userInput[1] = dateFormat.
                format(newReleaseDate.getDate() );
        userInput[2] = newRatingTxt.getText();
        userInput[3] = newDescriptionTxt.getText();
        userInput[4] = newRuntimeTxt.getText();
        userInput[5] = newSerialcodeTxt.getText();
        
        return userInput;
    }
    
    private MovieRequestHandler movieRequestHandler;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewProfileBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField newDescriptionTxt;
    private javax.swing.JPanel newProfilePanel;
    private javax.swing.JTextField newProfileTitleTxt;
    private javax.swing.JTextField newRatingTxt;
    private org.jdesktop.swingx.JXDatePicker newReleaseDate;
    private javax.swing.JTextField newRuntimeTxt;
    private javax.swing.JTextField newSerialcodeTxt;
    // End of variables declaration//GEN-END:variables
}
